version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dailylitbits
    restart: always
    ports:
      - "8002:8000"
    volumes:
      # Map the local src folder to /app inside container for live updates
      - ../src:/app
    env_file:
      - ../.env
    # Connect to the private BlueHorseshoe network
    networks:
      - backend_net

# Define the network connection
networks:
  backend_net:
    name: docker_app_net
    external: true
